name: Node.js tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build w/ Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
